# Generated by Django 3.1.2 on 2021-03-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.FloatField()),
                ('Y', models.FloatField()),
                ('Unique_Squirrel_ID', models.CharField(max_length=50)),
                ('Hectare', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=10)),
                ('Shift', models.CharField(max_length=10)),
                ('Date', models.IntegerField()),
                ('Hectare_Squirrel_Number', models.IntegerField()),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], max_length=20)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], max_length=20)),
                ('Combination_of_Primary_and_Highlight_Color', models.CharField(max_length=40)),
                ('Color_notes', models.CharField(blank=True, max_length=60)),
                ('Location', models.CharField(max_length=30)),
                ('Above_Ground_Sighter_Measurement', models.CharField(max_length=10)),
                ('Specific_Location', models.CharField(max_length=40)),
                ('Running', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=10)),
                ('Chasing', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=10)),
                ('Climbing', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=10)),
                ('Eating', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=10)),
                ('Foraging', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=10)),
                ('Other_Activities', models.CharField(blank=True, max_length=30)),
                ('Kuks', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=10)),
                ('Quaas', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=10)),
                ('Moans', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=10)),
                ('Tail_flags', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=10)),
                ('Tail_twitches', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=10)),
                ('Approaches', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=10)),
                ('Indifferent', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=10)),
                ('Runs_from', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=10)),
                ('Other_Interactions', models.CharField(blank=True, max_length=40)),
                ('Lat_Long', models.CharField(max_length=80)),
            ],
        ),
    ]
